baseURL = 'https://rinseo.github.io/'
languageCode = "en-US"
title = "Rinseo Park"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpg"
  author = "Rinseo Park"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "rinseo"
  Email         = "rinseo@yonsei.ac.kr"
  #Twitter       = "username"
  #LinkedIn      = "username"
  #Stackoverflow = "username"
  #Medium        = "username"
  #Telegram      = "username"
  #RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
