<<<<<<< HEAD
baseURL = 'http://rinseo.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
=======
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
>>>>>>> 3f9597e (first commit)
